---
version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Sweden/Stockholm
      - WEBUI_PORT=8081
    ports:
      - 8081:8081
    volumes:
      - ./qbittorrent/config:/config
      - Media:/data
    restart: unless-stopped

volumes:
 Media:
  driver_opts:
   type: cifs
   device: 
   o: 
