---
version: "2.1"
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - ./appdata/config:/config
      - ./backups:/backups
      - /mnt/hades:/hades
      - ~/:/host-home
    ports:
      - 8200:8200
    restart: unless-stopped
