version: '3'
services:
  bazarr:
    image: 'lscr.io/linuxserver/bazarr:latest'
    container_name: 'bazarr'
    environment:
      - 'PUID=1000'
      - 'PGID=1000'
      - 'TZ=Europe/Stockholm'
    volumes:
      - './bazarr/config:/config'
      - 'jellyfin_media:/data'
    ports:
      - '6767:6767/tcp'
    restart: 'unless-stopped'

  prowlarr:
    image: 'lscr.io/linuxserver/prowlarr:latest'
    container_name: 'prowlarr'
    environment:
      - 'PUID=1000'
      - 'PGID=1000'
      - 'TZ=Europe/Stockholm'
    volumes:
      - './prowlar/data:/config'
    ports:
      - '9696:9696/tcp'
    restart: 'unless-stopped'

  radarr:
    image: 'lscr.io/linuxserver/radarr:latest'
    container_name: 'radarr'
    environment:
      - 'PUID=1000'
      - 'PGID=1000'
      - 'TZ=Europe/Stockholm'
    volumes:
      - './radarr/config:/config'
      - 'jellyfin_media:/data'
    ports:
      - '7878:7878/tcp'
    restart: 'unless-stopped'
  sonarr:
    image: 'lscr.io/linuxserver/sonarr:latest'
    container_name: 'sonarr'
    environment:
      - 'PUID=1000'
      - 'PGID=1000'
      - 'TZ=Europe/Stockholm'
    volumes:
      - './sonarr/config:/config'
      - 'jellyfin_media:/data'
    ports:
      - '8989:8989/tcp'
    restart: 'unless-stopped'
  readarr:
    image: 'lscr.io/linuxserver/readarr:develop'
    container_name: 'readarr'
    environment:
      - 'PUID=1000'
      - 'PGID=1000'
      - 'TZ=Europe/Stockholm'
    volumes:
      - './readarr/config:/config'
      - 'jellyfin_media:/data' #optional
    ports:
      - '8787:8787'
    restart: 'unless-stopped'

volumes:
  jellyfin_media:
    driver_opts:
      type: cifs
      device: 
      o: 
