---
title: 'ProxHosted'
subtitle: 'SelfHosted'
logo: 'logo.png'

header: false
footer: '' # Set false if you want to hide it.

stylesheet:
  - 'assets/custom.css'

columns: '3' # You can change this to any number that is a factor of 12: (1, 2, 3, 4, 6, 12)
theme: default
colors:
  light:
    highlight-primary: '#fff5f2'
    highlight-secondary: '#fff5f2'
    highlight-hover: '#bebebe'
    background: '#12152B'
    card-background: 'rgba(255, 245, 242, 0.8)'
    text: '#ffffff'
    text-header: '#fafafa'
    text-title: '#000000'
    text-subtitle: '#111111'
    card-shadow: rgba(0, 0, 0, 0.5)
    link: '#3273dc'
    link-hover: '#2e4053'
    background-image: '../assets/wallpaper-light.jpeg' # Change wallpaper.jpeg to the name of your own custom wallpaper!
  dark:
    highlight-primary: '#181C3A'
    highlight-secondary: '#181C3A'
    highlight-hover: '#1F2347'
    background: '#12152B'
    card-background: 'rgba(24, 28, 58, 0.8)'
    text: '#eaeaea'
    text-header: '#7C71DD'
    text-title: '#fafafa'
    text-subtitle: '#8B8D9C'
    card-shadow: rgba(0, 0, 0, 0.5)
    link: '#c1c1c1'
    link-hover: '#fafafa'
    background-image: '../assets/wallpaper.jpeg'

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: 'Media'
    icon: 'fas fa-cloud'
    items:
      - name: 'Radarr'
        logo: 'assets/tools/radarr.png'
        subtitle: 'Movie Indexer'
        tag: 'indexer'
        keywords: 'self hosted radarr'
        url: 'https://radarr.ekstromhomelab.com'
      - name: 'Sonarr'
        logo: 'assets/tools/sonarr.png'
        subtitle: 'Show Indexer'
        tag: 'indexer'
        url: 'https://sonarr.ekstromhomelab.com'
      - name: 'qBittorrent'
        logo: 'assets/tools/qbittorrent.png'
        subtitle: 'Torrent Client'
        tag: 'torrent'
        url: 'https://qbittorrent.ekstromhomelab.com'
      - name: 'qBittorrent-leech'
        logo: 'assets/tools/qbittorrent.png'
        subtitle: 'Torrent Client'
        tag: 'torrent'
        url: 'https://qleech.ekstromhomelab.com'
      - name: 'Jellyfin'
        logo: 'assets/tools/jellyfin.png'
        subtitle: 'Mediaplayer'
        tag: 'mediaserver'
        url: 'https://jellyfin.ekstromhomelab.com'
      - name: 'Prowlarr'
        logo: 'assets/tools/prowlarr.png'
        subtitle: 'Index Manager'
        tag: 'Indexer'
        url: 'https://prowlarr.ekstromhomelab.com'
      - name: 'Jellyseerr'
        logo: 'assets/tools/jellyseerr.png'
        subtitle: 'Media Manager'
        tag: 'Media'
        url: 'https://jellyseerr.ekstromhomelab.com'
  - name: 'VPN/DNS/PROXY'
    icon: 'fas fa-cloud'
    items:
      - name: 'Pihole'
        logo: 'assets/tools/pihole.png'
        subtitle: 'DNS Server'
        tag: 'dns'
        url: 'https://pihole.ekstromhomelab.com/admin/login.php'
      - name: 'Tailscale'
        logo: 'assets/tools/tailscale.png'
        subtitle: 'VPN'
        tag: 'vpn'
        url: 'https://login.tailscale.com/admin/machines'
      - name: 'Traefik'
        logo: 'assets/tools/traefik.png'
        subtitle: 'Reverse Proxy'
        tag: 'proxy'
        url: 'https://traefik.ekstromhomelab.com'
  - name: 'Admin'
    icon: 'fas fa-cloud'
    items:
      - name: 'Uptime Kuma'
        logo: 'assets/tools/uptimekuma.png'
        subtitle: 'Container Monitoring'
        tag: 'monitoring'
        url: 'https://uptime.ekstromhomelab.com'
      - name: 'Portainer'
        logo: 'assets/tools/portainer.png'
        subtitle: 'Container Manager'
        tag: 'container'
        url: 'https://portainer.ekstromhomelab.com'
      - name: 'Proxmox'
        logo: 'assets/tools/proxmox.png'
        subtitle: 'Big Boss'
        tag: 've'
        url: 'https://proxmox.ekstromhomelab.com'
      - name: 'Home Assistant'
        logo: 'assets/tools/homeassistant.png'
        subtitle: 'Automation'
        tag: 'ha'
        url: 'http://homeassistant.local:8123/'
      - name: 'Home Assistant Pihole'
        logo: 'assets/tools/homeassistant.png'
        subtitle: 'Automation'
        tag: 'haPI'
        url: 'https://homeassistantpi.ekstromhomelab.com'
  - name: 'Storage/Backup'
    icon: 'fas fa-cloud'
    items:
      - name: 'True Nas'
        logo: 'assets/tools/truenas.png'
        subtitle: 'NAS Storage'
        tag: 'nas'
        url: 'https://truenas.ekstromhomelab.com'
      - name: 'InfluxDB'
        logo: 'assets/tools/influxdb.png'
        subtitle: 'DB'
        tag: 'influx'
        url: 'https://influxdb.ekstromhomelab.com'
      - name: 'DupliJelly'
        logo: 'assets/tools/dupli.png'
        subtitle: 'Backup'
        tag: 'backup'
        url: 'https://duplijelly.ekstromhomelab.com'
      - name: 'DupliQbit'
        logo: 'assets/tools/dupli.png'
        subtitle: 'Backup'
        tag: 'backup'
        url: 'https://dupliqbit.ekstromhomelab.com'
  - name: 'Visualization/Planing/SmartHome'
    icon: 'fas fa-cloud'
    items:
      - name: 'Grafana'
        logo: 'assets/tools/grafana.png'
        subtitle: 'Visualization'
        tag: 'grafana'
        url: 'https://grafana.ekstromhomelab.com'
      - name: 'Vikunja'
        logo: 'assets/tools/vikunja.png'
        subtitle: 'Planing'
        tag: 'planing'
        url: 'https://vikunja.ekstromhomelab.com'
      - name: 'DiyHue'
        logo: 'assets/tools/diyhue.png'
        subtitle: 'SmartHome'
        tag: 'smarthome'
        url: 'https://diyhue.ekstromhomelab.com'
      - name: Zigbee2MQTT
        logo: 'assets/tools/zigbee2mqtt.png'
        subtitle: 'SmartHome'
        tag: 'smarthome'
        url: 'https://zigbee2mqtt.ekstromhomelab.com'
